/*
 * Generated by TASKING Pin Mapper for AURIX
 * - device  : TC26x
 * - package : QFP144
 */

#include "aurix_pin_mappings.h"


/* GPIO pin configuration */

static const IfxPort_Io_ConfigPin gpio_pin_table[] = 
{
    IFXCFG_P00_0_IO_CONFIG,
    IFXCFG_P00_1_IO_CONFIG,
    IFXCFG_P00_2_IO_CONFIG,
    IFXCFG_P00_3_IO_CONFIG,
    IFXCFG_P00_4_IO_CONFIG,
    IFXCFG_P00_5_IO_CONFIG,
    IFXCFG_P00_6_IO_CONFIG,
    IFXCFG_P00_7_IO_CONFIG,
    IFXCFG_P02_3_IO_CONFIG,
    IFXCFG_P02_4_IO_CONFIG,
    IFXCFG_P02_5_IO_CONFIG,
    IFXCFG_P02_6_IO_CONFIG,
    IFXCFG_P15_1_IO_CONFIG,
    IFXCFG_P20_10_IO_CONFIG,
    IFXCFG_P20_13_IO_CONFIG,
    IFXCFG_P21_2_IO_CONFIG,
    IFXCFG_P21_3_IO_CONFIG,
    IFXCFG_P21_4_IO_CONFIG,
    IFXCFG_P21_5_IO_CONFIG,
    IFXCFG_P33_8_IO_CONFIG,
    IFXCFG_P33_9_IO_CONFIG,
    IFXCFG_P33_10_IO_CONFIG,
    IFXCFG_P33_11_IO_CONFIG
};

static const IfxPort_Io_Config gpio_io_config_table = 
{
    sizeof(gpio_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)gpio_pin_table
};

extern void gpio_init_pins(void)
{
    IfxPort_Io_initModule(&gpio_io_config_table);
}


/* ASCLIN1 pin configuration */

static const IfxPort_Io_ConfigPin asclin1_pin_table[] = 
{
    IFXCFG_P11_10_IO_CONFIG,
    IFXCFG_P11_12_IO_CONFIG
};

static const IfxPort_Io_Config asclin1_io_config_table = 
{
    sizeof(asclin1_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)asclin1_pin_table
};

extern void asclin1_init_pins(void)
{
    IfxPort_Io_initModule(&asclin1_io_config_table);
}


/* DAP3P pin configuration */

static const IfxPort_Io_ConfigPin dap3p_pin_table[] = 
{
    IFXCFG_P21_7_IO_CONFIG
};

static const IfxPort_Io_Config dap3p_io_config_table = 
{
    sizeof(dap3p_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)dap3p_pin_table
};

extern void dap3p_init_pins(void)
{
    IfxPort_Io_initModule(&dap3p_io_config_table);
}


/* ERUIN2 pin configuration */

static const IfxPort_Io_ConfigPin eruin2_pin_table[] = 
{
    IFXCFG_P02_1_IO_CONFIG
};

static const IfxPort_Io_Config eruin2_io_config_table = 
{
    sizeof(eruin2_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)eruin2_pin_table
};

extern void eruin2_init_pins(void)
{
    IfxPort_Io_initModule(&eruin2_io_config_table);
}


/* ERUIN4 pin configuration */

static const IfxPort_Io_ConfigPin eruin4_pin_table[] = 
{
    IFXCFG_P15_5_IO_CONFIG
};

static const IfxPort_Io_Config eruin4_io_config_table = 
{
    sizeof(eruin4_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)eruin4_pin_table
};

extern void eruin4_init_pins(void)
{
    IfxPort_Io_initModule(&eruin4_io_config_table);
}


/* ERUIN7 pin configuration */

static const IfxPort_Io_ConfigPin eruin7_pin_table[] = 
{
    IFXCFG_P20_9_IO_CONFIG
};

static const IfxPort_Io_Config eruin7_io_config_table = 
{
    sizeof(eruin7_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)eruin7_pin_table
};

extern void eruin7_init_pins(void)
{
    IfxPort_Io_initModule(&eruin7_io_config_table);
}


/* GTM0_TIM0_CH6 pin configuration */

static const IfxPort_Io_ConfigPin gtm0_tim0_ch6_pin_table[] = 
{
    IFXCFG_P20_0_IO_CONFIG
};

static const IfxPort_Io_Config gtm0_tim0_ch6_io_config_table = 
{
    sizeof(gtm0_tim0_ch6_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)gtm0_tim0_ch6_pin_table
};

extern void gtm0_tim0_ch6_init_pins(void)
{
    IfxPort_Io_initModule(&gtm0_tim0_ch6_io_config_table);
}


/* I2C0 pin configuration */

static const IfxPort_Io_ConfigPin i2c0_pin_table[] = 
{
    IFXCFG_P13_1_IO_CONFIG,
    IFXCFG_P13_2_IO_CONFIG
};

static const IfxPort_Io_Config i2c0_io_config_table = 
{
    sizeof(i2c0_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)i2c0_pin_table
};

extern void i2c0_init_pins(void)
{
    IfxPort_Io_initModule(&i2c0_io_config_table);
}


/* T12CCU0 pin configuration */

static const IfxPort_Io_ConfigPin t12ccu0_pin_table[] = 
{
    IFXCFG_P02_8_IO_CONFIG
};

static const IfxPort_Io_Config t12ccu0_io_config_table = 
{
    sizeof(t12ccu0_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)t12ccu0_pin_table
};

extern void t12ccu0_init_pins(void)
{
    IfxPort_Io_initModule(&t12ccu0_io_config_table);
}


/* T12CCU1 pin configuration */

static const IfxPort_Io_ConfigPin t12ccu1_pin_table[] = 
{
    IFXCFG_P20_11_IO_CONFIG
};

static const IfxPort_Io_Config t12ccu1_io_config_table = 
{
    sizeof(t12ccu1_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)t12ccu1_pin_table
};

extern void t12ccu1_init_pins(void)
{
    IfxPort_Io_initModule(&t12ccu1_io_config_table);
}


/* TOUT104 pin configuration */

static const IfxPort_Io_ConfigPin tout104_pin_table[] = 
{
    IFXCFG_P10_2_IO_CONFIG
};

static const IfxPort_Io_Config tout104_io_config_table = 
{
    sizeof(tout104_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)tout104_pin_table
};

extern void tout104_init_pins(void)
{
    IfxPort_Io_initModule(&tout104_io_config_table);
}


/* TOUT105 pin configuration */

static const IfxPort_Io_ConfigPin tout105_pin_table[] = 
{
    IFXCFG_P10_3_IO_CONFIG
};

static const IfxPort_Io_Config tout105_io_config_table = 
{
    sizeof(tout105_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)tout105_pin_table
};

extern void tout105_init_pins(void)
{
    IfxPort_Io_initModule(&tout105_io_config_table);
}

