/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "XinDongLib/XinDong_INCLUDED.h"

IfxCpu_syncEvent g_cpuSyncEvent = 0;
uint8 temp;

int core0_main(void){
	/* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
	 * Enable the watchdogs and service them periodically if it is required
	 */
	IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
	IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

	/* Wait for CPU sync event */
	IfxCpu_emitEvent(&g_cpuSyncEvent);
	IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

	// disable the interrupts
	IfxCpu_disableInterrupts();

	/* User Code Begin 1 */
	gpio_init();
//	ultrasonic_trigger();
//	encoder_init();
	gtm_init();
//	tim_init();
//	tom_initServo();
//	tom_initMotor();
	uart1_init();
	camera_init();

	stm0_installInterrupts();
	camera_installInterrupts();
//	encoder_installInterrupt();
//	ble_installInterrupts();
//	ultrasonic_installInterrupt();
//	reed_installInterrupt();
//	tim_installInterrupts();

// enable the interrupts
	IfxCpu_enableInterrupts();

	while(1){
		temp = camera_getFlag();
		if(temp == 2){
			IfxPort_togglePin(&MODULE_P33, 11);
		}
		delay_ms(10);
	}
	return (1);
}

void encoder_step(void){
	__asm("NOP");__asm("NOP");__asm("NOP");
}

void periodicInterrupt_10ms(void){
	__asm("NOP");__asm("NOP");__asm("NOP");
//    gpio_setLED1(gpio_readDIP1());
//    gpio_setLED2(gpio_readDIP2());
//    gpio_setLED3(gpio_readDIP3());
//    gpio_setLED4(gpio_readDIP4());
}

void periodicInterrupt_100ms(void){
	__asm("NOP");__asm("NOP");__asm("NOP");
}

void periodicInterrupt_1s(void){
	__asm("NOP");__asm("NOP");__asm("NOP");

	IfxPort_togglePin(&MODULE_P33, 10);
}

void reed_triggered(void){
	__asm("NOP");__asm("NOP");__asm("NOP");
}

void ultrasonic_gotNewValue(void){
	__asm("NOP");__asm("NOP");__asm("NOP");
}
