/*
 * Generated by TASKING Pin Mapper for AURIX
 * - device  : TC26x
 * - package : QFP144
 */

#include "aurix_pin_mappings.h"


/* DAP3P pin configuration */

static const IfxPort_Io_ConfigPin dap3p_pin_table[] = 
{
    IFXCFG_P21_7_IO_CONFIG
};

static const IfxPort_Io_Config dap3p_io_config_table = 
{
    sizeof(dap3p_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)dap3p_pin_table
};

extern void dap3p_init_pins(void)
{
    IfxPort_Io_initModule(&dap3p_io_config_table);
}

