/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "CameraShenyan.h"
#include "Hardware.h"
#include "UserSource.h"
IfxCpu_syncEvent g_cpuSyncEvent = 0;

int core0_main (void)
{

    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    IfxCpu_disableInterrupts();
    GpioInit();//初始化编码开关
    STM_InitConfig(STM0, STM_Channel_0, 10000);//STM初始化
    GTM_Clocks_Init();
    AsclinAsc_init();
    PIN_InitConfig(P33_8,IfxPort_Mode_outputPushPullGeneral,0);
    PIN_InitConfig(P33_9,IfxPort_Mode_outputPushPullGeneral,0);
    PIN_InitConfig(P33_10,IfxPort_Mode_outputPushPullGeneral,0);
    PIN_InitConfig(P33_11,IfxPort_Mode_outputPushPullGeneral,0);
    TOM0_init(); //PWM0 output --- P20.11
    TOM1_init();//PWM1 output--- P10.2
    TOM2_init();//PWM2 output--- P10.3
    Tim_init();//摄像头 编码器 超声 输入捕获初始化
    UltrasoundInit();
    mpu6050_Init();//初始化iic Mpu6050
    CoderInit();//编码器初始化
    CAMERA_Init(30);
    IfxCpu_enableInterrupts();
    while (1)
    {
//        Asclin_Send_String("AA");
        UserCpu0Main();
    }
    return (1);
}
